"use client";

import { motion } from "framer-motion";
import { useState, useEffect } from "react";
import {
  DocumentTextIcon,
  PaperAirplaneIcon,
  CreditCardIcon,
  ArrowsRightLeftIcon,
  BookOpenIcon,
  ChartBarIcon,
  CheckIcon,
} from "@heroicons/react/24/outline";

interface WorkflowStep {
  id: string;
  title: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
}

const workflowSteps: WorkflowStep[] = [
  {
    id: "generate",
    title: "Invoice Generated",
    description: "Automatically generated by system",
    icon: DocumentTextIcon,
  },
  {
    id: "send",
    title: "Sent to Client",
    description: "Automatically sent by system",
    icon: PaperAirplaneIcon,
  },
  {
    id: "pay",
    title: "Client Payment",
    description: "Invoice is paid by client",
    icon: CreditCardIcon,
  },
  {
    id: "reconcile",
    title: "Payment Reconciled",
    description: "Automatically matched to invoice",
    icon: ArrowsRightLeftIcon,
  },
  {
    id: "update",
    title: "Ledgers Updated",
    description: "Journal entries automatically updated",
    icon: BookOpenIcon,
  },
  {
    id: "report",
    title: "Reports Generated",
    description: "Financial reports automatically created",
    icon: ChartBarIcon,
  },
];

const ANIMATION_DURATION = 3000;

export function AutomatedWorkflow() {
  const [activeStep, setActiveStep] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setActiveStep((prev) => (prev + 1) % workflowSteps.length);
    }, ANIMATION_DURATION);

    return () => clearInterval(interval);
  }, []);

  return (
    <div className="w-full">
      <div className="relative max-w-7xl mx-auto px-4 md:px-8">
        <div className="relative flex flex-col md:flex-row items-start md:items-center justify-between gap-12 md:gap-4 lg:gap-8">
          {workflowSteps.map((step, index) => {
            const Icon = step.icon;
            const isActive = activeStep === index;
            const isCompleted = activeStep > index;
            const isLast = index === workflowSteps.length - 1;

            return (
              <div key={step.id} className="relative flex-1 flex flex-col items-center">
                {/* Connecting line/arrow - hidden on mobile, shown on desktop */}
                {!isLast && (
                  <div className="hidden md:block absolute top-8 left-1/2 w-full h-0.5 pointer-events-none">
                    <motion.div
                      className="h-full bg-white/30"
                      initial={{ width: 0 }}
                      animate={{ width: isCompleted ? "100%" : activeStep === index ? "50%" : "0%" }}
                      transition={{ duration: 0.5 }}
                    />
                    <div className="absolute right-0 top-1/2 -translate-y-1/2 w-0 h-0 border-l-[6px] border-l-white/30 border-t-[3px] border-t-transparent border-b-[3px] border-b-transparent" />
                  </div>
                )}

                {/* Step container */}
                <motion.div
                  className="relative mb-6"
                  animate={{
                    scale: isActive ? 1.05 : 1,
                  }}
                  transition={{
                    type: "spring",
                    stiffness: 300,
                    damping: 20,
                  }}
                >
                  {/* Background circle */}
                  <div
                    className={`absolute w-16 h-16 rounded-full left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 transition-all duration-300 ${
                      isActive
                        ? "bg-white/10 scale-110"
                        : isCompleted
                        ? "bg-white/5"
                        : "bg-transparent"
                    }`}
                  />

                  {/* Icon */}
                  <div className="relative w-16 h-16 flex items-center justify-center">
                    <Icon
                      className={`w-8 h-8 transition-colors duration-300 ${
                        isActive
                          ? "text-white"
                          : isCompleted
                          ? "text-white/80"
                          : "text-white/50"
                      }`}
                    />
                  </div>

                  {/* Active indicator */}
                  {isActive && (
                    <motion.div
                      className="absolute -bottom-2 left-1/2 -translate-x-1/2 w-2 h-2 rounded-full bg-white"
                      initial={{ scale: 0 }}
                      animate={{
                        scale: [1, 1.3, 1],
                      }}
                      transition={{
                        duration: 1.5,
                        repeat: Infinity,
                        ease: "easeInOut",
                      }}
                    />
                  )}

                  {/* Completed checkmark */}
                  {isCompleted && (
                    <motion.div
                      className="absolute -bottom-2 left-1/2 -translate-x-1/2 w-5 h-5 rounded-full bg-white flex items-center justify-center shadow-sm"
                      initial={{ scale: 0, rotate: -180 }}
                      animate={{ scale: 1, rotate: 0 }}
                      transition={{
                        type: "spring",
                        stiffness: 200,
                        damping: 15,
                      }}
                    >
                      <CheckIcon className="w-3 h-3 text-black" />
                    </motion.div>
                  )}

                  {/* Step number badge */}
                  <div
                    className={`absolute -top-1 -right-1 w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-medium transition-colors ${
                      isActive
                        ? "bg-white text-black"
                        : "bg-white/20 text-white/80"
                    }`}
                  >
                    {index + 1}
                  </div>
                </motion.div>

                {/* Title */}
                <h3
                  className={`text-sm md:text-base font-medium mb-1.5 text-center transition-colors duration-300 ${
                    isActive
                      ? "text-white"
                      : isCompleted
                      ? "text-white/90"
                      : "text-white/70"
                  }`}
                >
                  {step.title}
                </h3>

                {/* Description */}
                <p
                  className={`text-xs md:text-sm text-center leading-relaxed transition-colors duration-300 ${
                    isActive
                      ? "text-white/90"
                      : isCompleted
                      ? "text-white/70"
                      : "text-white/60"
                  }`}
                >
                  {step.description}
                </p>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
